# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import helloworld_pb2 as helloworld__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/apb.api.user.UserService/RegisterUser',
                request_serializer=helloworld__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=helloworld__pb2.RegisterUserResponse.FromString,
                )
        self.Auth = channel.unary_unary(
                '/apb.api.user.UserService/Auth',
                request_serializer=helloworld__pb2.AuthUserRequest.SerializeToString,
                response_deserializer=helloworld__pb2.AuthUserResponse.FromString,
                )
        self.GameStart = channel.unary_unary(
                '/apb.api.user.UserService/GameStart',
                request_serializer=helloworld__pb2.GameStartReq.SerializeToString,
                response_deserializer=helloworld__pb2.GameStartRes.FromString,
                )


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Auth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GameStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=helloworld__pb2.RegisterUserRequest.FromString,
                    response_serializer=helloworld__pb2.RegisterUserResponse.SerializeToString,
            ),
            'Auth': grpc.unary_unary_rpc_method_handler(
                    servicer.Auth,
                    request_deserializer=helloworld__pb2.AuthUserRequest.FromString,
                    response_serializer=helloworld__pb2.AuthUserResponse.SerializeToString,
            ),
            'GameStart': grpc.unary_unary_rpc_method_handler(
                    servicer.GameStart,
                    request_deserializer=helloworld__pb2.GameStartReq.FromString,
                    response_serializer=helloworld__pb2.GameStartRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apb.api.user.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apb.api.user.UserService/RegisterUser',
            helloworld__pb2.RegisterUserRequest.SerializeToString,
            helloworld__pb2.RegisterUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Auth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apb.api.user.UserService/Auth',
            helloworld__pb2.AuthUserRequest.SerializeToString,
            helloworld__pb2.AuthUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GameStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/apb.api.user.UserService/GameStart',
            helloworld__pb2.GameStartReq.SerializeToString,
            helloworld__pb2.GameStartRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
