#!/bin/bash
killall Python
cd /Users/xuzhengda/Documents/codespace_pc/netw/
/usr/local/bin/python nese.py fl > log/fl
/usr/local/bin/python nese.py qjq 10108 5 > log/qjq
/usr/local/bin/python nese.py qh > log/qh
/usr/local/bin/python nese.py cf > log/cf
# /usr/local/bin/python nese.py qn xnds 1> log/qe
/usr/local/bin/python nese.py qn za11 1> log/qe
/usr/local/bin/python nese.py qn za31 1> log/qe
/usr/local/bin/python nese.py qn za41 1> log/qe

/usr/local/bin/python nese.py qn za71 1> log/qe
/usr/local/bin/python nese.py qn za81 1> log/qe

/usr/local/bin/python nese.py sb > log/sb
/usr/local/bin/python nese.py mrck > log/mrck

